name: Build & Test Python Wheel Package

on:
  push:
    paths:
      - "src/**"
      - "tests/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install qiskit qiskit-aer qiskit-ibm-runtime
      - name: Generate wheel package
        run: python -m pip wheel -w wheel .
      - name: Upload wheel package
        uses: actions/upload-artifact@v4
        with:
          name: wheel-pkg
          path: wheel/qiskit_leaky_scheduling*.whl
          if-no-files-found: error
          retention-days: 1
          overwrite: true

  test:
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: tests
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Download wheel package
        uses: actions/download-artifact@v4
        with:
          name: wheel-pkg
      - name: Install wheel package
        run: python -m pip install *.whl
      - name: Run tests
        run: python -m unittest discover tests

